apiVersion: v2
name: flowable
version: 6.7.3-snapshot.1
description: A Flowable Helm chart for Kubernetes
appVersion: 6.7.2
home: https://flowable.org
icon: https://flowable.org/docs/img/logo.png
artifacthub.io/prerelease: "true"