flowable:
  host:
    external: 34.90.219.164
  # Global database name, user and password
  database:
    name: flowable
    username: flowable
    password: flowable

ingress:
  enabled: true
  sslRedirect: false

idm:
  enabled: true
  replicas: 1
  service:
    name: flowable-idm
  contextUrl: /
  image:
    repository: flowable/flowable-idm
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
  javaOpts: "-Xmx1g -Xms1g"

# Enable either Flowable Task or Flowable REST
task:
  enabled: true
  replicas: 1
  service:
    name: flowable-task
  contextUrl: /
  image:
    repository: flowable/flowable-task
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
  javaOpts: "-Xmx1g -Xms1g"

# Enable either Flowable Task or Flowable REST
rest:
  enabled: false
  replicas: 1
  service:
    name: flowable-rest
  image:
    repository: flowable/flowable-rest
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  javaOpts: "-Xmx1g -Xms1g"

modeler:
  enabled: true
  replicas: 1
  service:
    name: flowable-modeler
  contextUrl: /
  image:
    repository: flowable/flowable-modeler
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
  javaOpts: "-Xmx1g -Xms1g"

admin:
  enabled: true
  replicas: 1
  service:
    name: flowable-admin
  contextUrl: /
  image:
    repository: flowable/flowable-admin
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
  javaOpts: "-Xmx1g -Xms1g"

rest:
  enabled: false
  replicas: 1
  service:
    name: flowable-rest
  contextUrl: /
  image:
    repository: flowable/flowable-rest
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "1Gi"
  javaOpts: "-Xmx1g -Xms1g"

# NGINX Ingress controller https://github.com/kubernetes/ingress-nginx
nginx-ingress:
  rbac:
    create: true
  # the controller will set the endpoint records on the ingress objects to reflect those on the service
  controller:
    publishService:
      enabled: true

postgres:
  enabled: true
  service:
    name: postgres
  image: postgres:9.6
  storage:
    storageClassName: "standard"
#    storageClassName: "ssd"
    size: 1Gi
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
