apiVersion: v2
name: flowable
version: 7.0.0-beta.1
description: A Flowable Helm chart for Kubernetes
appVersion: 7.0.0
home: https://www.flowable.com/open-source
icon: https://www.flowable.com/open-source/docs/img/logo.png
sources:
  - https://github.com/flowable/flowable-engine/
keywords:
  - flowable
  - BPMN
  - CMMN
  - DMN
maintainers:
  - name: yvoswillens
    email: yvoswillens@gmail.com
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.10.0
    condition: postgres.enabled
    alias: postgres
annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/images: |
    - name: Flowable REST
      image: flowable/flowable-rest:7.0.0
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Flowable OSS repository
      url: https://link1.url
    - name: Flowable OSS website
      url: https://www.flowable.com/open-source
  artifacthub.io/signKey: |
    fingerprint: B3B09108406A7DFE92757807A79624786AE252EB
    url: https://keybase.io/flowable_oss/pgp_keys.asc
