name: Lint and Test Charts

on: pull_request

jobs:
  chart-testing:
    name: Lint and Test kubernetes ${{ matrix.kubernetesVersion }}
    strategy:
      fail-fast: false
      matrix:
        kubernetesVersion: [
          "v1.22.9",
          "v1.23.6",
          "v1.24.0"
        ]

    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          version: v3.5.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.3.0
        with:
          node_image: "kindest/node:${{ matrix.kubernetesVersion }}"
        if: steps.list-changed.outputs.changed == 'true'

      - name: Verify kind
        run: |
          kubectl cluster-info
          kubectl get nodes -o wide
          kubectl get pods -n kube-system
        # Only build a kind cluster if there are chart changes to test.
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml